const QUIZZES={
"Carreira e Competências para o Mercado de Trabalho em Administração":[
["Semana 19 • Público-alvo","Uma empresa percebe que seu produto não precisa atender todas as pessoas. Ela procura identificar quem possui características, interesses e necessidades semelhantes. Esse grupo ajuda a empresa a direcionar melhor sua solução.","O que melhor define público-alvo?",["Qualquer pessoa que tenha interesse geral.","Apenas pessoas que já compraram o produto.","Um grupo com características e necessidades semelhantes.","Todas as pessoas que conhecem o produto."],2],
["Semana 19 • Cliente","Antes de criar uma solução, é importante conhecer quem irá utilizá-la. Quando uma empresa entende as necessidades, dificuldades e características de seu público, consegue desenvolver algo mais adequado para essas pessoas.","Por que compreender o cliente é fundamental antes de desenvolver uma solução?",["Para diminuir os custos do projeto.","Para reduzir o tempo de execução.","Para simplificar o trabalho em equipe.","Para garantir alinhamento com as necessidades do público-alvo."],3],
["Semana 19 • Necessidades","Nem sempre uma compra acontece apenas pela utilidade do produto. Algumas pessoas também procuram demonstrar sua posição, estilo ou reconhecimento diante de outras pessoas. Nesse caso, a compra está relacionada à maneira como a pessoa deseja ser percebida socialmente.","Uma pessoa compra um relógio caro principalmente para demonstrar status. Que tipo de necessidade está sendo atendido?",["Técnica","Financeira","Social","Prática"],2],
["Semana 19 • Canvas","Ao desenvolver uma ideia, pode ser difícil visualizar como todas as partes da solução se relacionam. O Canvas ajuda a organizar essas informações de maneira visual e estruturada, facilitando a compreensão da ideia e de seu funcionamento.","Qual é a principal importância do uso do Modelo de Negócios Canvas?",["Reduzir a participação da equipe.","Aumentar a clareza e a compreensão da solução.","Substituir o plano de negócios completo.","Aumentar a complexidade da ideia."],1],
["Semana 19 • Recursos-chave","Para que uma solução funcione, ela precisa contar com determinados recursos. Eles podem incluir equipamentos, pessoas, conhecimentos ou tecnologias necessários para colocar a ideia em prática. Sem esses elementos, a solução pode não funcionar como planejado.","Uma ideia depende de tecnologia para funcionar, mas isso não foi considerado no planejamento. Qual bloco foi ignorado?",["Recursos-chave","Canais","Custos","Parcerias"],0],
["Semana 19 • Feedback","Uma ideia pode parecer excelente para quem a criou, mas apresentar dificuldades quando outras pessoas a experimentam. Por isso, ouvir opiniões externas ajuda a perceber problemas, compreender diferentes perspectivas e fazer melhorias na solução.","Durante o teste de uma ideia, o feedback de outras pessoas permite:",["Validar definitivamente a solução proposta.","Substituir a etapa de planejamento.","Diminuir o tempo de trabalho.","Analisar percepções externas para melhorar a solução."],3],
["Semana 20 • Canvas","Um grupo de estudantes teve uma ideia de negócio, mas percebeu que havia muitas informações espalhadas. Ao colocar clientes, atividades, recursos e outros elementos em um único modelo visual, o grupo conseguiu enxergar melhor como sua ideia funcionaria.","Qual é a principal importância do uso do Modelo de Negócios Canvas?",["Reduzir a participação da equipe.","Aumentar a complexidade da ideia.","Substituir o plano de negócios completo.","Aumentar a clareza e a compreensão da solução."],3],
["Semana 20 • Recursos-chave","Um grupo criou um aplicativo, mas só depois percebeu que precisava de computadores, sistemas e conhecimentos técnicos para desenvolvê-lo. Esses elementos são necessários para que a solução possa realmente funcionar.","Qual bloco do Canvas foi ignorado?",["Recursos-chave","Parcerias","Custos","Canais"],0],
["Semana 20 • Feedback","Depois de apresentar uma solução, o grupo pediu que outras pessoas experimentassem a ideia. Algumas gostaram, enquanto outras apontaram dificuldades. Essas opiniões ajudaram o grupo a perceber o que poderia ser melhorado.","Durante o teste de uma ideia, o feedback permite:",["Substituir a etapa de planejamento.","Analisar percepções externas para melhorar a solução.","Diminuir o tempo de trabalho.","Validar definitivamente a solução proposta."],1],
["Semana 21 • Renda líquida","Ao receber seu salário, uma pessoa percebe que o valor depositado em sua conta é menor que o salário contratado. Isso acontece porque alguns valores foram descontados antes do pagamento chegar até ela. O dinheiro que efetivamente fica disponível para utilização é chamado de renda líquida.","O valor que efetivamente fica disponível para uso é chamado de:",["Renda líquida","Receita variável","Renda bruta","Reserva financeira"],0],
["Semana 21 • Gasto variável","Algumas despesas aparecem praticamente todos os meses e são mais previsíveis. Outras dependem das escolhas realizadas durante o mês, como atividades de lazer. Quanto mais uma pessoa escolhe realizar determinada atividade, maior pode ser esse gasto.","Qual das opções representa um gasto variável?",["Internet","Aluguel","Conta de luz","Cinema"],3],
["Semana 21 • Organização financeira","Ao registrar o dinheiro que entra e sai, uma pessoa percebeu que estava gastando com coisas que não eram prioridade. Com essa informação, passou a analisar melhor suas escolhas e a decidir onde utilizar seu dinheiro.","Qual foi o principal benefício da organização financeira?",["Eliminar todas as despesas do mês.","Tomar decisões financeiras mais conscientes.","Garantir aumento da renda mensal.","Eliminar completamente os gastos variáveis."],1],
["Semana 22 • Meta financeira","Uma pessoa deseja melhorar sua vida financeira, mas percebe que apenas desejar não é suficiente. Para transformar uma intenção em meta, ela precisa estabelecer algo concreto que possa acompanhar ao longo do tempo, como um valor que será guardado regularmente.","Qual alternativa apresenta corretamente um exemplo de meta financeira?",["Desejar uma vida financeira tranquila.","Conquistar estabilidade financeira futuramente.","Guardar R$ 150 mensais durante 1 ano.","Ter mais qualidade de vida financeira."],2],
["Semana 22 • OKR","Uma estudante estabelece um objetivo e define resultados que deseja alcançar. Durante o período planejado, ela acompanha seus avanços para saber se está se aproximando do que pretendia. Dessa forma, consegue observar metas e resultados.","O uso do OKR no planejamento pessoal ou profissional pode contribuir principalmente para:",["Acompanhar metas e resultados.","Eliminar todos os riscos financeiros.","Garantir sucesso imediato nos planos.","Evitar mudanças de objetivos."],0],
["Semana 22 • Resultado-chave","Uma pessoa define o objetivo de melhorar sua vida financeira. Para acompanhar esse objetivo, ela estabelece uma ação que possa ser medida concretamente todos os meses. Um valor mensal guardado permite verificar objetivamente seu progresso.","Qual alternativa apresenta corretamente um exemplo de resultado-chave (KR)?",["Ter independência financeira.","Guardar R$ 100 por mês.","Melhorar minha organização pessoal.","Sonhar com estabilidade financeira."],1],
["Semana 23 • Lifelong Learning","As profissões mudam constantemente e novas tecnologias passam a fazer parte do trabalho. Por isso, profissionais precisam continuar aprendendo ao longo da vida para acompanhar novas ferramentas, conhecimentos e transformações que surgem no mercado.","Nesse contexto, o Lifelong Learning se torna importante porque permite:",["Acompanhar transformações do mercado.","Trabalhar sem atualização constante.","Evitar mudanças profissionais.","Substituir experiências profissionais."],0],
["Semana 23 • Aprender a conhecer","Um estudante quer compreender melhor sua área profissional. Para isso, pesquisa informações, lê notícias, assiste a vídeos e consulta diferentes fontes. Seu objetivo principal é ampliar seus conhecimentos e compreender melhor aquilo que está estudando.","Essa atitude está relacionada a qual pilar?",["Aprender a fazer","Aprender a ser","Aprender a conhecer","Aprender a conviver"],2],
["Semana 23 • Aprender a conviver","Durante um projeto, os estudantes dividiram tarefas, ouviram opiniões diferentes e colaboraram para alcançar um resultado comum. A experiência valorizou a convivência e a colaboração.","Essa experiência se relaciona a qual pilar?",["Aprender a ser","Aprender a conviver","Aprender a fazer","Aprender a conhecer"],1],
["Semana 23 • PDI","Um PDI ajuda a organizar objetivos pessoais e profissionais. Com ele, o estudante pode identificar metas, reconhecer habilidades que precisam ser desenvolvidas, planejar ações e acompanhar a própria evolução.","Qual é uma finalidade do Plano de Desenvolvimento Individual (PDI)?",["Eliminar a necessidade de aprendizagem.","Organizar objetivos, ações e acompanhar a evolução.","Substituir todas as experiências profissionais.","Evitar mudanças de objetivos."],1],
["Semana 24 • Organização da apresentação","Durante uma apresentação de PDI, o estudante precisa mostrar sua trajetória, seus objetivos e seu desenvolvimento. Quando as informações aparecem em uma sequência organizada, fica mais fácil compreender a relação entre passado, presente e futuro profissional.","Qual estratégia favorece maior coerência na apresentação?",["Organização lógica dos tópicos.","Uso frequente de improvisação.","Leitura integral do roteiro.","Uso excessivo de detalhes técnicos."],0],
["Semana 24 • Feedback","Depois de uma apresentação, o feedback pode ajudar o colega a perceber o que fez bem e o que ainda pode melhorar. Para ser útil, a avaliação deve ser respeitosa, reconhecendo os pontos positivos e apresentando sugestões de melhoria.","Ao oferecer feedback após a apresentação de um colega, qual atitude é mais adequada?",["Avaliar exclusivamente a postura e o tom de voz.","Destacar pontos fortes e sugerir melhorias com respeito.","Corrigir o colega na apresentação para não esquecer nada.","Comparar a apresentação com a de outros colegas."],1],
["Semana 24 • Escuta ativa","Em uma discussão, cada participante pode trazer experiências e opiniões diferentes. Quando as pessoas realmente escutam umas às outras, conseguem compreender perspectivas que talvez não conhecessem e reconhecer que existem diferentes trajetórias.","A escuta ativa é importante principalmente para:",["Selecionar apenas experiências profissionais positivas.","Tornar as discussões mais curtas e objetivas.","Valorizar diferentes trajetórias e perspectivas.","Garantir respostas padronizadas."],2]
],
"Introdução a Administração, Legislação e Pessoas":[]
};